version: '3.9'

services:
  db:
    image: postgres:14-alpine
    ports:
      - "5435:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./db/create-slim-db.sql:/docker-entrypoint-initdb.d/create-slim-db.sql
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=scans
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./db/create-slim-db.sql:/docker-entrypoint-initdb.d/create-slim-db.sql