import random

_ADJECTIVES = [
    "mundane","murky","mushy","mute","mysterious",
    "naive","nappy","narrow","nasty","natural",
    "naughty","nauseating","near","neat","nebulous",
    "necessary","needless","needy","neighborly","nervous",
    "new","next","nice","nifty","nimble",
    "nine","nippy","noiseless","noisy","nonchalant",
    "nondescript","nonstop","normal","nostalgic","nosy",
    "noxious","null","numberless","numerous","nutritious",
    "nutty", "oafish","obedient","obeisant","obese",
    "obnoxious","obscene","obsequious","observant","obsolete",
    "obtainable","oceanic","odd","offbeat","old",
    "omniscient","one","onerous","open","opposite",
    "optimal","orange","ordinary","organic","ossified",
    "outgoing","outrageous","outstanding","oval","overconfident",
    "overjoyed","overrated","overt","overwrought", "painful",
    "painstaking","pale","paltry","panicky","panoramic",
    "parallel","parched","parsimonious","past","pastoral",
    "pathetic","peaceful","penitent","perfect","periodic",
    "permissible","perpetual","petite","petite","phobic",
    "physical","picayune","pink","piquant","placid",
    "plain","plant","plastic","plausible","pleasant",
    "plucky","pointless","poised","polite","political",
    "poor","possessive","possible","powerful","precious",
    "premium","present","pretty","previous","pricey",
    "prickly","private","probable","productive","profuse",
    "protective","proud","psychedelic","psychotic","public",
    "puffy","pumped","puny","purple","purring",
    "pushy","puzzled","puzzling", "quack","quaint",
    "quarrelsome","questionable","quick","quickest","quiet",
    "quirky","quixotic","quizzical", "rabid","racial",
    "ragged","rainy","rambunctious","rampant","rapid",
    "rare","raspy","ratty","ready","real",
    "rebel","receptive","recondite","red","redundant",
    "reflective","regular","relieved","remarkable","reminiscent",
    "repulsive","resolute","resonant","responsible","rhetorical",
    "rich","right","righteous","rightful","rigid",
    "ripe","ritzy","roasted","robust","romantic",
    "roomy","rotten","rough","round","royal",
    "ruddy","rude","rural","rustic","ruthless",
    "sable","sad","safe","salty","same",
    "sassy","satisfying","savory","scandalous","scarce",
    "scared","scary","scattered","scientific","scintillating",
    "scrawny","screeching","second","secret","secretive",
    "sedate","seemly","selective","selfish","separate",
    "serious","shaggy","shaky","shallow","sharp",
    "shiny","shivering","shocking","short","shrill",
    "shut","shy","sick","silent","silent",
    "silky","silly","simple","simplistic","sincere",
    "six","skillful","skinny","sleepy","slim",
    "slimy","slippery","sloppy","slow","small",
    "smart","smelly","smiling","smoggy","smooth",
    "sneaky","snobbish","snotty","soft","soggy",
    "solid","somber","sophisticated","sordid","sore",
    "sore","sour","sparkling","special","spectacular",
    "spicy","spiffy","spiky","spiritual","spiteful",
    "splendid","spooky","spotless","spotted","spotty",
    "spurious","squalid","square","squealing","squeamish",
    "staking","stale","standing","statuesque","steadfast",
    "steady","steep","stereotyped","sticky","stiff",
    "stimulating","stingy","stormy","straight","strange",
    "striped","strong","stupendous","stupid","sturdy",
    "subdued","subsequent","substantial","successful","succinct",
    "sudden","sulky","super","superb","superficial",
    "supreme","swanky","sweet","sweltering","swift",
    "symptomatic","synonymous", "taboo","tacit","tacky",
    "talented","tall","tame","tan","tangible",
    "tangy","tart","tasteful","tasteless","tasty",
    "tawdry","tearful","tedious","teeny","telling",
    "temporary","ten","tender","tense","tense",
    "tenuous","terrible","terrific","tested","testy",
    "thankful","therapeutic","thick","thin","thinkable",
    "third","thirsty","thirsty","thoughtful","thoughtless",
    "threatening","three","thundering","tidy","tight",
    "tightfisted","tiny","tired","tiresome","toothsome",
    "torpid","tough","towering","tranquil","trashy",
    "tremendous","tricky","trite","troubled","truculent",
    "true","truthful","two","typical", "ubiquitous",
    "ugliest","ugly","ultra","unable","unaccountable",
    "unadvised","unarmed","unbecoming","unbiased","uncovered",
    "understood","undesirable","unequal","unequaled","uneven",
    "unhealthy","uninterested","unique","unkempt","unknown",
    "unnatural","unruly","unsightly","unsuitable","untidy",
    "unused","unusual","unwieldy","unwritten","upbeat",
    "uppity","upset","uptight","used","useful",
    "useless","utopian","utter","uttermost", "vacuous",
    "vagabond","vague","valuable","various","vast",
    "vengeful","venomous","verdant","versed","victorious",
    "vigorous","violent","violet","vivacious","voiceless",
    "volatile","voracious","vulgar", "wacky","waggish",
    "waiting","wakeful","wandering","wanting","warlike",
    "warm","wary","wasteful","watery","weak",
    "wealthy","weary","wet","whimsical","whispering",
    "white","whole","wholesale","wicked","wide",
    "wiggly","wild","willing","windy","wiry",
    "wise","wistful","witty","woebegone","womanly",
    "wonderful","wooden","woozy","workable","worried",
    "worthless","wrathful","wretched","wrong","wry",
    "xenophobic","yellow","yielding","young","youthful",
    "yummy","zany","zealous","zesty","zippy",
    "zonked",
]

_NAMES = [
    "Liam", "Noah", "Oliver", "James", "Elijah", "William",
    "Henry", "Lucas", "Benjamin", "Theodore", "Mateo", "Levi",
    "Sebastian", "Daniel", "Jack", "Michael", "Alexander", "Owen",
    "Asher", "Samuel", "Ethan", "Leo", "Jackson", "Mason",
    "Ezra", "John", "Hudson", "Luca", "Aiden", "Joseph",
    "David", "Jacob", "Logan", "Luke", "Julian", "Gabriel",
    "Grayson", "Wyatt", "Matthew", "Maverick", "Dylan", "Isaac",
    "Elias", "Anthony", "Thomas", "Jayden", "Carter", "Santiago",
    "Ezekiel", "Charles", "Josiah", "Caleb", "Cooper", "Lincoln",
    "Miles", "Christopher", "Nathan", "Isaiah", "Kai", "Joshua",
    "Andrew", "Angel", "Adrian", "Cameron", "Nolan", "Waylon",
    "Jaxon", "Roman", "Eli", "Wesley", "Aaron", "Ian",
    "Christian", "Ryan", "Leonardo", "Brooks", "Axel", "Walker",
    "Jonathan", "Easton", "Everett", "Weston", "Bennett", "Robert",
    "Jameson", "Landon", "Silas", "Jose", "Beau", "Micah",
    "Colton", "Jordan", "Jeremiah", "Parker", "Greyson", "Rowan",
    "Adam", "Nicholas", "Theo", "Xavier", "Hunter", "Dominic",
    "Jace", "Gael", "River", "Thiago", "Kayden", "Damian",
    "August", "Carson", "Austin", "Myles", "Amir", "Declan",
    "Emmett", "Ryder", "Luka", "Connor", "Jaxson", "Milo",
    "Enzo", "Giovanni", "Vincent", "Diego", "Luis", "Archer",
    "Harrison", "Kingston", "Atlas", "Jasper", "Sawyer", "Legend",
    "Lorenzo", "Evan", "Jonah", "Chase", "Bryson", "Adriel",
    "Nathaniel", "Arthur", "Juan", "George", "Cole", "Zion",
    "Jason", "Ashton", "Carlos", "Calvin", "Brayden", "Elliot",
    "Rhett", "Emiliano", "Ace", "Jayce", "Graham", "Max",
    "Braxton", "Leon", "Ivan", "Hayden", "Jude", "Malachi",
    "Dean", "Tyler", "Jesus", "Zachary", "Kaiden", "Elliott",
    "Arlo", "Emmanuel", "Ayden", "Bentley", "Maxwell", "Amari",
    "Ryker", "Finn", "Antonio", "Charlie", "Maddox", "Justin",
    "Judah", "Kevin", "Dawson", "Matteo", "Miguel", "Zayden",
    "Camden", "Messiah", "Alan", "Alex", "Nicolas", "Felix",
    "Alejandro", "Jesse", "Beckett", "Matias", "Tucker", "Emilio",
    "Xander", "Knox", "Oscar", "Beckham", "Timothy", "Abraham",
    "Andres", "Gavin", "Brody", "Barrett", "Hayes", "Jett",
    "Brandon", "Joel", "Victor", "Peter", "Abel", "Edward",
    "Karter", "Patrick", "Richard", "Grant", "Avery", "King",
    "Caden", "Adonis", "Riley", "Tristan", "Kyrie", "Blake",
    "Eric", "Griffin", "Malakai", "Rafael", "Israel", "Tate",
    "Lukas", "Nico", "Marcus", "Stetson", "Javier", "Colt",
    "Omar", "Simon", "Kash", "Remington", "Jeremy", "Louis",
    "Mark", "Lennox", "Callum", "Kairo", "Nash", "Kyler",
    "Dallas", "Crew", "Preston", "Paxton", "Steven", "Zane",
    "Kaleb", "Lane", "Phoenix", "Paul", "Cash", "Kenneth",
    "Bryce", "Ronan", "Kaden", "Maximiliano", "Walter", "Maximus",
    "Emerson", "Hendrix", "Jax", "Atticus", "Zayn", "Tobias",
    "Cohen", "Aziel", "Kayson", "Rory", "Brady", "Finley",
    "Holden", "Jorge", "Malcolm", "Clayton", "Niko", "Francisco",
    "Josue", "Brian", "Bryan", "Cade", "Colin", "Andre",
    "Cayden", "Aidan", "Muhammad", "Derek", "Ali", "Elian",
    "Bodhi", "Cody", "Jensen", "Damien", "Martin", "Cairo",
    "Ellis", "Khalil", "Otto", "Zander", "Dante", "Ismael",
    "Angelo", "Brantley", "Manuel", "Colson", "Cruz", "Tatum",
    "Jaylen", "Jaden", "Erick", "Cristian", "Romeo", "Milan",
    "Reid", "Cyrus", "Leonel", "Joaquin", "Ari", "Odin",
    "Orion", "Ezequiel", "Gideon", "Daxton", "Warren", "Casey",
    "Anderson", "Spencer", "Karson", "Eduardo", "Chance", "Fernando",
    "Raymond", "Bradley", "Cesar", "Wade", "Prince", "Julius",
    "Dakota", "Kade", "Koa", "Raiden", "Callan", "Hector",
    "Onyx", "Remy", "Ricardo", "Edwin", "Stephen", "Kane",
    "Saint", "Titus", "Desmond", "Killian", "Sullivan", "Mario",
    "Jay", "Kamari", "Luciano", "Royal", "Zyaire", "Marco",
    "Wilder", "Russell", "Nasir", "Rylan", "Archie", "Jared",
    "Gianni", "Kashton", "Kobe", "Sergio", "Travis", "Marshall",
    "Iker", "Briggs", "Gunner", "Apollo", "Bowen", "Baylor",
    "Sage", "Tyson", "Kyle", "Oakley", "Malik", "Mathias",
    "Sean", "Armani", "Hugo", "Johnny", "Sterling", "Forrest",
    "Harvey", "Banks", "Grady", "Kameron", "Jake", "Franklin",
    "Lawson", "Tanner", "Eden", "Jaziel", "Pablo", "Reed",
    "Pedro", "Zayne", "Royce", "Edgar", "Ibrahim", "Winston",
    "Ronin", "Leonidas", "Devin", "Damon", "Noel", "Rhys",
    "Clark", "Corbin", "Sonny", "Colter", "Esteban", "Erik",
    "Baker", "Adan", "Dariel", "Kylo", "Tripp", "Caiden",
    "Frank", "Solomon", "Major", "Memphis", "Quinn", "Dax",
    "Hank", "Donovan", "Finnegan", "Nehemiah", "Andy", "Camilo",
    "Asa", "Jeffrey", "Santino", "Isaias", "Jaiden", "Kian",
    "Fabian", "Callen", "Ruben", "Alexis", "Emanuel", "Francis",
    "Garrett", "Kendrick", "Matthias", "Wells", "Augustus", "Jasiah",
    "Alijah", "Alonzo", "Koda", "Collin", "Ford", "Frederick",
    "Jaxton", "Kohen", "Troy", "Kason", "Seth", "Denver",
    "Kyson", "Ares", "Raphael", "Bodie", "Sylas", "Uriel",
    "Zaiden", "Shiloh", "Lewis", "Kieran", "Marcos", "Bo",
    "Shepherd", "Philip", "Zaire", "Gregory", "Princeton", "Roberto",
    "Leland", "Eithan", "Moshe", "Johnathan", "Lucca", "Kenzo",
    "Mack", "Porter", "Kolton", "Kaison", "Valentino", "Saul",
    "Shane", "Jamari", "Rocco", "Kylan", "Deacon", "Dalton",
    "Moses", "Callahan", "Tadeo", "Makai", "Amiri", "Rowen",
    "Drew", "Jalen", "Kylian", "Sutton", "Dominick", "Reece",
    "Rodrigo", "Soren", "Kasen", "Ridge", "Zachariah", "Jamir",
    "Peyton", "Omari", "Trevor", "Morgan", "Izaiah", "Alessandro",
    "Kaysen", "Enrique", "Marcelo", "Sincere", "Lucian", "Leandro",
    "Armando", "Braylen", "Jayson", "Julio", "Lawrence", "Cassius",
    "Raul", "Jase", "Mohammad", "Zain", "Jayceon", "Jonas",
    "Ronald", "Ayaan", "Rio", "Allen", "Bruce", "Mohamed",
    "Dorian", "Maximilian", "Keegan", "Shawn", "Yusuf", "Pierce",
    "Ariel", "Ander", "Conor", "Conrad", "Phillip", "Arjun",
    "Roy", "Moises", "Arturo", "Johan", "Gerardo", "Atreus",
    "Nikolai", "Braylon", "Samson", "Hezekiah", "Kayce", "Scott",
    "Gunnar", "Jamison", "Samir", "Keanu", "Ledger", "Jaime",
    "Finnley", "Cannon", "Colby", "Nikolas", "Emmitt", "Kamden",
    "Miller", "Boone", "Hamza", "Ocean", "Mac", "Anakin",
    "Brixton", "Roland", "Huxley", "Zeke", "Danny", "Marvin",
    "Otis", "Albert", "Clay", "Emir", "Boston", "Bruno",
    "Lionel", "Ozzy", "Taylor", "Jamie", "Augustine", "Chaim",
    "Krew", "Rayan", "Alden", "Bellamy", "Amos", "Drake",
    "Davis", "Dustin", "Corey", "Ahmad", "Conner", "Gustavo",
    "Layton", "Abram", "Axton", "Chandler", "Azariah", "Reese",
    "Benson", "Tru", "Case", "Trey", "Mauricio", "Westin",
    "Gage", "Reign", "Creed", "Mylo", "Dennis", "Quentin",
    "Madden", "Rome", "Julien", "Sam", "Zaid", "Marcel",
    "Maximo", "Layne", "Ahmed", "Kannon", "Quincy", "Yosef",
    "Aarav", "Lennon", "Ryland", "Skyler", "Chris", "Eliam",
    "Kareem", "Kyree", "Dario", "Donald", "Fletcher", "Darius",
    "Duke", "Rayden", "Salem", "Vicente", "Vincenzo", "Cayson",
    "Eliseo", "Issac", "Lian", "Clyde", "Wilson", "Santana",
    "Tomas", "Dexter", "Keith", "Houston", "Harry", "Uriah",
    "Lee", "Rex", "Tony", "Carmelo", "Alberto", "Loyal",
    "Trace", "Alfredo", "Riggs", "Forest", "Raylan", "Salvador",
    "Jakari", "Zakai", "Louie", "Flynn", "Leonard", "Mohammed",
    "Derrick", "Musa", "Avi", "Ty", "Westley", "Ambrose",
    "Brycen", "Aron", "Caspian", "Gatlin", "Harlan", "Dillon",
    "Emery", "Nixon", "Tommy", "Watson", "Zayd", "Azrael",
    "Zyair", "Azriel", "Legacy", "Cillian", "Alvin", "Bridger",
    "Alec", "Edison", "Kingsley", "Remi", "Briar", "Jaxxon",
    "Truett", "Lachlan", "Cal", "Landen", "Roger", "Alonso",
    "Kaiser", "Blaze", "Jerry", "Seven", "Kenji", "Noe",
    "Quinton", "Grey", "Jefferson", "Marcellus", "Ray", "Kyro",
    "Benicio", "Justice", "Neil", "Idris", "Bear", "Kiaan",
    "Wayne", "Ben", "Junior", "Karim", "Yehuda", "Jimmy",
    "Ramon", "Bjorn", "Nathanael", "Stanley", "Hassan", "Magnus",
    "Trenton", "Brayan", "Brock", "Jagger", "Cason", "Dakari",
    "Rey", "Abdiel", "Abdullah", "Casen", "Jiraiya", "Lance",
    "Misael", "Alvaro", "Robin", "Langston", "Nelson", "Wes",
    "Khari", "Landyn", "Jakai", "Lochlan", "Valentin", "Keaton",
    "Amias", "Joziah", "Thaddeus", "Jedidiah", "Orlando", "Eliel",
    "Hugh", "Koen", "Calum", "Enoch", "Mitchell", "Rohan",
    "Aryan", "Dilan", "Aden", "Allan", "Leighton", "Elisha",
    "Evander", "Castiel", "Curtis", "Kellen", "Dash", "Douglas",
    "Eddie", "Melvin", "Avyaan", "Everest", "Zamir", "Ricky",
    "Dutton", "Yahir", "Devon", "Franco", "Khaza", "Dior",
    "Leif", "Sevyn", "Guillermo", "Ira", "Emory", "Felipe",
    "Titan", "Alfred", "Azael", "Zahir", "Kellan", "Darren",
    "Rudy", "Ayan", "Leroy", "Anders", "Ishaan", "Reuben",
    "Boden", "Mccoy", "Heath", "Kase", "Wylder", "Judson",
    "Khai", "Kye", "Axl", "Crue", "Ernesto", "Ahmir",
    "Zyon", "Aries", "Mustafa", "Santos", "Dane", "Damari",
    "Elio", "Jadiel", "Jovanni", "Salvatore", "Mathew", "Kolson",
    "Nova", "Brendan", "Murphy", "Brodie", "Damir", "Rocky",
    "Larry", "Fisher", "Waylen", "Byron", "Ermias", "Joey",
    "Joe", "Jon", "Arian", "Chosen", "Jairo", "Vihaan",
    "Kylen", "Ameer", "Dion", "Jrue", "Kaizen", "Yousef",
    "Bryant", "Cullen", "Kaisen", "Kelvin", "Zen", "Kartier",
    "Randy", "Shepard", "Alaric", "Cain", "Jeremias", "Alfonso",
    "Brecken", "Colten", "Gian", "Rhodes", "Wesson", "Duncan",
    "Harold", "Henrik", "Harley", "Alistair", "Agustin", "Jericho",
    "Talon", "Westyn", "Cassian", "Eugene", "Ryatt", "Shmuel",
    "Braden", "Yahya", "Aldo", "Dangelo", "Ezrah", "Korbin",
    "Zavier", "Bronson", "Teo", "Jones", "Neo", "Stefan",
    "Van", "Mekhi", "Coleson", "Eren", "Ignacio", "Kristian",
    "Harlem", "Zev", "Canaan", "Cedric", "Khalid", "Bode",
    "Gary", "Rene", "Benedict", "Maxton", "Thatcher", "Wallace",
    "Davian", "Gordon", "Niklaus", "Yisroel", "Kabir", "Osman",
    "Adler", "Darian", "Terry", "Cartier", "Osiris", "Vance",
    "Demetrius", "Kamryn", "Lux", "Stone", "Jaxx", "Kooper",
    "Rodney", "Aurelio", "Darwin", "Jakob", "Zechariah", "Brennan",
    "Marlon", "Meir", "Yael", "Asaiah", "Atharv", "Imran",
    "Ivaan", "Kanan", "Kalel", "London",
]

def GetRandomName():
    return f"{random.choice(_ADJECTIVES)}_{random.choice(_NAMES)}".lower()

